#!/bin/bash
modprobe libcomposite
mount -t configfs none /sys/kernel/config

cd /sys/kernel/config/usb_gadget/
mkdir -p hid && cd hid

echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2

mkdir -p strings/0x409
echo "fedcba9876542069" > ./strings/0x409/serialnumber
echo "FranK" > ./strings/0x409/manufacturer
echo "USB Device" > ./strings/0x409/product

mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > ./configs/c.1/strings/0x409/configuration
echo 250 > ./configs/c.1/MaxPower

# begin functions
mkdir -p functions/hid.usb0
echo 1 > ./functions/hid.usb0/protocol
echo 1 > ./functions/hid.usb0/subclass
echo 5 > ./functions/hid.usb0/report_length
# hid descriptor - uses 16 bits for x and y offsets
echo -ne \\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x03\\x05\\x01\\x09\\x30\\x09\\x31\\x16\\x00\\x80\\x26\\xff\\x7f\\x75\\x10\\x95\\x02\\x81\\x06\\xc0\\xc0 > ./functions/hid.usb0/report_desc
ln -s ./functions/hid.usb0 configs/c.1/
# end functions

sleep 1

cat 20980000.usb > /sys/kernel/config/usb_gadget/hid/UDC
